### ISSUE TITLE
Create Release

### ISSUE THREAD

**Issue by phdoerfler** [lydgate/bmndr#5]
I wrote a [formula](https://github.com/phdoerfler/homebrew-core/blob/bmndr/Formula/bmndr.rb) for the homebrew package manager so macOS people can install bmndr in a nice way.
For it to be accepted by the homebrew people it should fetch a specific release version / specific release of bmndr instead of always fetching HEAD.

So, can we have a release please?

**Comment by lydgate** [comment]
Sorry for the delay! I've created release v1.0.0, with no changes to what's currently there.
